version: "3.8"

services:
  api:
    image: jobs:latest
    ports:
        - "8080:8080"
    restart: unless-stopped
    depends_on:
        - database # This service depends on db. Start that first.
    environment:
      PORT: ${PORT}
      ACCESS_SECRET: ${ACCESS_SECRET}
      CONTEXT_KEY: ${CONTEXT_KEY}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_SSL: ${DB_SSL}
    networks:
        - backend
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
        - backend

networks:
  backend: